spring:
  profiles:
    include: secret

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

tron:
  trongrid:
    base-url: https://nile.trongrid.io
    timeout-ms: 8000
  token:
    usdt-contract: "TXYZopYRdj2D9XRtbG411XZZ3kM5VkAeBf"
  wallet:
    server-address: "TBDCmYiKxyGBXnDFkivM3kpbAJs3twmW9L"
  polling:
    interval-ms: 3000
    batch-size: 50